# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_echeance', models.DateTimeField()),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_tva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('en_retard', 'En retard'), ('annulee', 'Annulée')], default='brouillon', max_length=50)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('contact_principal', models.CharField(max_length=100)),
                ('numero_siret', models.CharField(blank=True, max_length=14)),
                ('tva_applicable', models.BooleanField(default=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte bancaire'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('paypal', 'PayPal')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('refuse', 'Refusé'), ('rembourse', 'Remboursé')], default='en_attente', max_length=50)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('type_remise', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('utilisations_max', models.PositiveIntegerField(blank=True, null=True)),
                ('utilisations_actuelles', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Remise',
                'verbose_name_plural': 'Remises',
            },
        ),
        migrations.CreateModel(
            name='SponsoringOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_prise_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('montant_prise_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_accord', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('paye', 'Payé')], default='en_attente', max_length=50)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sponsoring Organisation',
                'verbose_name_plural': 'Sponsorings Organisations',
            },
        ),
    ]
