# Generated by Django 4.2.7 on 2025-07-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apprenant_organisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('organisme', models.CharField(blank=True, max_length=200)),
                ('date_obtention', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='formateur',
            name='parcours',
            field=models.TextField(blank=True, help_text='Expérience professionnelle, formation, licences et certifications'),
        ),
        migrations.RemoveField(
            model_name='formateur',
            name='competences',
        ),
        migrations.AddField(
            model_name='formateur',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='users.certification'),
        ),
        migrations.AddField(
            model_name='formateur',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='formateurs', to='users.competence'),
        ),
    ]
