# Generated by Django 4.2.7 on 2025-07-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_certification_competence_formateur_parcours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_deconnexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
