# Generated by Django 4.2.7 on 2025-07-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_utilisateur_derniere_deconnexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='confirmation',
            field=models.CharField(default='En cours', max_length=20),
        ),
    ]
