# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0002_initial'),
        ('payments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoringorganisation',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='sponsoringorganisation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AddField(
            model_name='sponsoringorganisation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.organisation'),
        ),
        migrations.AddField(
            model_name='remise',
            name='formations_eligibles',
            field=models.ManyToManyField(blank=True, to='formations.formation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='apprenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.organisation'),
        ),
        migrations.AddField(
            model_name='facture',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.paiement'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsoringorganisation',
            unique_together={('organisation', 'apprenant', 'formation')},
        ),
    ]
