# Generated by Django 4.2.7 on 2025-07-26 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('keyword', 'Mots-clés'), ('pattern', 'Expressions régulières'), ('sentiment', 'Analyse de sentiment'), ('toxicity', 'Détection de toxicité'), ('spam', 'Détection de spam')], max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Liste de mots-clés à détecter')),
                ('patterns', models.JSONField(blank=True, default=list, help_text='Expressions régulières')),
                ('threshold', models.FloatField(default=0.5, help_text='Seuil de détection (0.0 - 1.0)')),
                ('auto_block', models.BooleanField(default=False, help_text='Bloquer automatiquement le contenu')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de Modération',
                'verbose_name_plural': 'Règles de Modération',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModerationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_content_checked', models.PositiveIntegerField(default=0)),
                ('flagged_content', models.PositiveIntegerField(default=0)),
                ('auto_blocked', models.PositiveIntegerField(default=0)),
                ('human_reviewed', models.PositiveIntegerField(default=0)),
                ('false_positives', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistiques de Modération',
                'verbose_name_plural': 'Statistiques de Modération',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ContentModerationWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_type', models.CharField(choices=[('user', 'Utilisateur'), ('keyword', 'Mot-clé'), ('domain', 'Domaine'), ('phrase', 'Phrase')], max_length=20)),
                ('value', models.CharField(help_text='Valeur à autoriser', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste Blanche',
                'verbose_name_plural': 'Listes Blanches',
                'unique_together': {('whitelist_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ContentModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type_label', models.CharField(choices=[('course_comment', 'Commentaire de cours'), ('discussion_reply', 'Réponse de discussion'), ('group_message', 'Message de groupe'), ('private_message', 'Message privé'), ('formation_comment', 'Commentaire de formation'), ('task_description', 'Description de tâche')], max_length=50)),
                ('original_content', models.TextField(help_text='Contenu original signalé')),
                ('ai_confidence', models.FloatField(help_text="Confiance de l'IA (0.0 - 1.0)")),
                ('detected_issues', models.JSONField(default=list, help_text='Liste des problèmes détectés')),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewing', 'En révision'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('auto_filtered', 'Filtré automatiquement')], default='pending', max_length=20)),
                ('auto_blocked', models.BooleanField(default=False, help_text='Contenu bloqué automatiquement')),
                ('review_notes', models.TextField(blank=True, help_text='Notes du modérateur')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de Modération',
                'verbose_name_plural': 'Rapports de Modération',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='moderation__status_ffe317_idx'), models.Index(fields=['auto_blocked'], name='moderation__auto_bl_0fffda_idx'), models.Index(fields=['content_type', 'object_id'], name='moderation__content_7f0617_idx')],
            },
        ),
    ]
