# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('approuve', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Commentaire de Cours',
                'verbose_name_plural': 'Commentaires de Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contenu', models.TextField()),
                ('duree_minutes', models.PositiveIntegerField()),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=50)),
                ('categorie', models.CharField(max_length=100)),
                ('mots_cles', models.CharField(help_text='Mots-clés séparés par des virgules', max_length=500)),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='cours/')),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gratuit', models.BooleanField(default=False)),
                ('publie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProgressionCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('progression_pourcentage', models.PositiveIntegerField(default=0)),
                ('temps_passe_minutes', models.PositiveIntegerField(default=0)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('termine', models.BooleanField(default=False)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Progression de Cours',
                'verbose_name_plural': 'Progressions de Cours',
            },
        ),
        migrations.CreateModel(
            name='RessourceCours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_ressource', models.CharField(choices=[('video', 'Vidéo'), ('document', 'Document'), ('audio', 'Audio'), ('lien', 'Lien externe'), ('exercice', 'Exercice'), ('quiz', 'Quiz')], max_length=50)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='cours/ressources/')),
                ('lien_externe', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('obligatoire', models.BooleanField(default=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='courses.cours')),
            ],
            options={
                'verbose_name': 'Ressource de Cours',
                'verbose_name_plural': 'Ressources de Cours',
                'ordering': ['ordre'],
            },
        ),
    ]
