# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_attestation', models.CharField(max_length=50, unique=True)),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('competences_acquises', models.TextField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='attestations/')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_contenu', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('note_formateur', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('note_organisation', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('note_globale', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('recommande', models.BooleanField(default=True)),
                ('date_evaluation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objectifs', models.TextField()),
                ('duree_heures', models.PositiveIntegerField(help_text='Durée en heures')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participants_max', models.PositiveIntegerField(default=20)),
                ('prerequisites', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=50)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateTimeField()),
                ('duree_session', models.PositiveIntegerField(help_text='Durée en minutes')),
                ('sujet', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code_presence', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Plannings',
                'ordering': ['date_session'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('heure_arrivee', models.DateTimeField(blank=True, null=True)),
                ('heure_depart', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('localisation', models.CharField(max_length=200)),
                ('equipements', models.TextField(blank=True, help_text='Équipements disponibles')),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
    ]
