# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='presence',
            name='planning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.planning'),
        ),
        migrations.AddField(
            model_name='planning',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation'),
        ),
        migrations.AddField(
            model_name='planning',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.salle'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='formations_inscrites', to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='formations.formation'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('planning', 'apprenant')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('formation', 'apprenant')},
        ),
        migrations.AlterUniqueTogether(
            name='attestation',
            unique_together={('formation', 'apprenant')},
        ),
    ]
