# Generated by Django 4.2.7 on 2025-07-26 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formations', '0003_formation_applications_ouvertes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('priorite', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='todo', max_length=15, verbose_name='Statut')),
                ('categorie', models.CharField(choices=[('formation', 'Formation'), ('cours', 'Cours'), ('evaluation', 'Évaluation'), ('personnel', 'Personnel'), ('administratif', 'Administratif')], default='personnel', max_length=15, verbose_name='Catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_echeance', models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('date_completion', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('fichiers_attaches', models.FileField(blank=True, null=True, upload_to='tasks/attachments/', verbose_name='Fichiers attachés')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('formation_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formations.formation', verbose_name='Formation liée')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['createur', 'statut'], name='formations__createu_538ec1_idx'), models.Index(fields=['date_echeance'], name='formations__date_ec_a9faaa_idx'), models.Index(fields=['priorite'], name='formations__priorit_7ca31a_idx')],
            },
        ),
    ]
