# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncours',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='progressioncours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.cours'),
        ),
        migrations.AddField(
            model_name='progressioncours',
            name='ressources_completees',
            field=models.ManyToManyField(blank=True, to='courses.ressourcecours'),
        ),
        migrations.AddField(
            model_name='cours',
            name='formateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formateur'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='apprenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.apprenant'),
        ),
        migrations.AddField(
            model_name='commentairecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='courses.cours'),
        ),
        migrations.AlterUniqueTogether(
            name='progressioncours',
            unique_together={('cours', 'apprenant')},
        ),
    ]
