# Generated by Django 4.2.7 on 2025-07-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_badge_utilisateur_account_deletion_requested_and_more'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('seuil_reussite', models.PositiveIntegerField(default=60, help_text='Score minimum (%) pour réussir')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.cours')),
                ('ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='courses.ressourcecours')),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois')], default='week', max_length=10)),
                ('objectif_lecons', models.PositiveIntegerField(default=3)),
                ('lecons_terminees', models.PositiveIntegerField(default=0)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('atteint', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='users.apprenant')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('seuil_completion', models.PositiveIntegerField(default=80, help_text='% de progression requis pour certification')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='courses.cours')),
                ('quizzes_requis', models.ManyToManyField(blank=True, to='courses.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('date_passage', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='users.apprenant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='courses.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'apprenant')},
            },
        ),
        migrations.CreateModel(
            name='CertificationProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('apprenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_progresses', to='users.apprenant')),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='courses.certification')),
            ],
            options={
                'unique_together': {('certification', 'apprenant')},
            },
        ),
    ]
