# Generated by Django 4.2.7 on 2025-07-25 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('epingle', models.BooleanField(default=False)),
                ('ferme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('derniere_reponse', models.DateTimeField(blank=True, null=True)),
                ('nb_vues', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fil de Discussion',
                'verbose_name_plural': 'Fils de Discussion',
                'ordering': ['-epingle', '-derniere_reponse'],
            },
        ),
        migrations.CreateModel(
            name='GroupeChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prive', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Groupe de Chat',
                'verbose_name_plural': 'Groupes de Chat',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='messages/')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('lu', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='MessageGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='groupes/')),
                ('date_envoi', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Message de Groupe',
                'verbose_name_plural': 'Messages de Groupe',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='ReponseDiscussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier_joint', models.FileField(blank=True, null=True, upload_to='discussions/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifie', models.BooleanField(default=False)),
                ('date_modification', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Réponse de Discussion',
                'verbose_name_plural': 'Réponses de Discussion',
                'ordering': ['date_creation'],
            },
        ),
    ]
