# Generated by Django 4.2.7 on 2025-07-26 01:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('formations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='applications_ouvertes',
            field=models.BooleanField(default=False, help_text='Permet aux formateurs de candidater'),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_limite_candidature',
            field=models.DateTimeField(blank=True, help_text='Date limite pour candidater', null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('proposition', 'Proposition (candidatures ouvertes)'), ('publiee', 'Publiée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='brouillon', max_length=50),
        ),
        migrations.CreateModel(
            name='TrainerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Message de motivation ou présentation')),
                ('motivation', models.TextField(help_text='Pourquoi souhaitez-vous animer cette formation?')),
                ('experience_pertinente', models.TextField(help_text='Expérience pertinente pour cette formation')),
                ('tarif_propose', models.DecimalField(blank=True, decimal_places=2, help_text='Tarif horaire proposé', max_digits=8, null=True)),
                ('disponibilite', models.TextField(help_text='Créneaux de disponibilité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('rejetee', 'Rejetée'), ('retiree', 'Retirée')], default='en_attente', max_length=20)),
                ('date_candidature', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.TextField(blank=True, help_text="Commentaire de l'administrateur")),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.formateur')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_applications', to='formations.formation')),
            ],
            options={
                'verbose_name': 'Candidature Formateur',
                'verbose_name_plural': 'Candidatures Formateurs',
                'ordering': ['-date_candidature'],
                'unique_together': {('formation', 'formateur')},
            },
        ),
    ]
