# Generated by Django 4.2.7 on 2025-07-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('formations', '0005_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='cours',
            field=models.ManyToManyField(blank=True, related_name='formations', to='courses.cours'),
        ),
    ]
