# Generated by Django 4.2.7 on 2025-08-01 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_badge_utilisateur_account_deletion_requested_and_more'),
        ('formations', '0006_formation_cours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerapplication',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.formateur'),
        ),
        migrations.AlterField(
            model_name='trainerapplication',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_applications', to='formations.formation'),
        ),
    ]
