# Generated by Django 4.2.7 on 2025-08-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0007_alter_trainerapplication_formateur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerapplication',
            name='suggested_formation',
            field=models.CharField(blank=True, help_text='Formation suggérée par le candidat', max_length=255, null=True),
        ),
    ]
